// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Siphon.Bot.Data;

#nullable disable

namespace Siphon.Bot.Data.Migrations
{
    [DbContext(typeof(BotDb))]
    [Migration("20260719193045_ChatDeliveryOptions")]
    partial class ChatDeliveryOptions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Siphon.Bot.Data.CachedFile", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("Siphon.Bot.Data.ChatState", b =>
                {
                    b.Property<long>("ChatId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DayKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("DeleteSourceLink")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DownloadsToday")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lang")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastActivityUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ShowRequester")
                        .HasColumnType("INTEGER");

                    b.HasKey("ChatId");

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("Siphon.Bot.Data.GroupInfo", b =>
                {
                    b.Property<long>("ChatId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("OwnerUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ChatId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("Siphon.Bot.Data.UsageEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ChatId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Site")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Utc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Utc");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Siphon.Bot.Data.UserPref", b =>
                {
                    b.Property<long>("ChatId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Platform")
                        .HasColumnType("TEXT");

                    b.Property<string>("AudioFormat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Quality")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoFormat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ChatId", "Platform");

                    b.ToTable("Prefs");
                });
#pragma warning restore 612, 618
        }
    }
}
