<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Siphon.Media\Siphon.Media.csproj" />
    <ProjectReference Include="..\Siphon.Accounts\Siphon.Accounts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
    <PackageReference Include="Microsoft.OpenApi" Version="2.11.0" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.16.15" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <Target Name="CopyWebDist" BeforeTargets="Build" Condition="Exists('..\..\web\dist\siphon-web')">
    <ItemGroup>
      <WebDist Include="..\..\web\dist\siphon-web\**\*" />
    </ItemGroup>
    <Copy SourceFiles="@(WebDist)" DestinationFiles="@(WebDist->'wwwroot\%(RecursiveDir)%(Filename)%(Extension)')" SkipUnchangedFiles="true" />
  </Target>

</Project>
